GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTk0NTE5OTQsImV4cCI6MTY5OTQ1NTU5NCwiYXVkIjoiNjU0YjhiY2EwYjU3OWU2NjY4NGIxODUwIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.8RUCXRrodpdKVR3TDrtcyUz61wN4R2U3eT5eCOuf0qI
###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "AYOUB.OUESLATI10@gmail.com",
    "password": "1234"
     
}

###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "AYOUB.OUESLATI14@gmail.com",
    "password": "1234"

}

###Refresh token  Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTk0NTIwMDUsImV4cCI6MTY5OTQ1MjAzNSwiYXVkIjoiNjU0YjhiY2EwYjU3OWU2NjY4NGIxODUwIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ._qTKe0LZfePo5V5Qw7S8Aw4h_-Plo02CRxB74vLI0Lw" 
}

###logout Route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTk0NTIwMDUsImV4cCI6MTY5OTQ1MjAzNSwiYXVkIjoiNjU0YjhiY2EwYjU3OWU2NjY4NGIxODUwIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ._qTKe0LZfePo5V5Qw7S8Aw4h_-Plo02CRxB74vLI0Lw" 
}